### ISSUE TITLE
Deployment code doesn't work when trying to override DATABASE_URL

### ISSUE THREAD

**Issue by ryansch** [bkeepers/dotenv-deployment#10]
I need to load dotenv before I can boot my rails application.  As such, I can't call Rails.root without getting a nil response.  It would be useful for me to be able to use dotenv-deployment and pass a path to the configuration directory to glob instead of chaining off of Rails.root.

For now, I'll basically copy/paste deployment.rb.

**Comment by bkeepers** [comment]
This gem has been deprecated. See https://github.com/bkeepers/dotenv-deployment/pull/29
