### ISSUE TITLE
Lack of .env files in config/** reverts any .env.#{environment}

### ISSUE THREAD

**Issue by dlindahl** [bkeepers/dotenv-deployment#13]
In a Rails app, if there are no `.env` files in `config/**/`, `dotenv` [adds](https://github.com/bkeepers/dotenv/blob/8f1bc8c53d3cea88870401273f4dfaa9ef24fe16/lib/dotenv.rb#L22) (and parses) the root `.env` file, reverting any overrides in `.env.#{environment}`

For example:

```
# in /.env
FOO=root

# in /.env.development
FOO=dev
```

```ruby
Dotenv.load '.env'
pp ENV['FOO']
# > "root"

Dotenv.overload ".env.#{environment}"
pp ENV['FOO']
# > "dev"

Dotenv.overload *Dir.glob("#{Rails.root}/config/**/*.env.#{environment}")
pp ENV['FOO']
# > "root"
```

The `glob` call returns an empty array which is then backfilled with `.env` in [`Dotenv#with`](https://github.com/bkeepers/dotenv/blob/8f1bc8c53d3cea88870401273f4dfaa9ef24fe16/lib/dotenv.rb#L22). This means that the non-environment specific file is not only parsed twice, it reverts anything that is overridden in `.env.development`

**Comment by PikachuEXE** [comment]
Still not fixed?

**Comment by rypit** [comment]
This doesn't occur in versions of dotenv before this gem was created, so you may be able to use something like `dotenv 0.9.0`. Which seems to load correctly with various `RAILS_ENV` settings, if that's all you're looking for.
