### ISSUE TITLE
Unicorn in Production

### ISSUE THREAD

**Issue by joelmats** [bkeepers/dotenv-deployment#16]
It seems that environment is set to RACK_ENV which is 'deployment' when using unicorn. I prefer my .env to be named .env.production rather than .env.deployment so it might be better to prioritize Rails.env over RACK_ENV when Rails.env is available.

**Comment by dideler** [comment]
Has this caused any issues for you or did you go with `.env.deployment`?

**Comment by joelmats** [comment]
I just went with deployment with some comments at the top in case anyone is confused :P

**Comment by bkeepers** [comment]
This gem has been deprecated. See https://github.com/bkeepers/dotenv-deployment/pull/29
