### ISSUE TITLE
If spring is running dotenv data is cached

### ISSUE THREAD

**Issue by kwerle** [bkeepers/dotenv-deployment#24]
Configure a rails app to use spring.

edit:
.env: FOO=bar

rails runner "puts ENV['FOO']"
bar

edit:
.env: FOO=baZ

rails runner "puts ENV['FOO']"
bar

Sad panda.

**Comment by bkeepers** [comment]
This gem has been deprecated. See https://github.com/bkeepers/dotenv-deployment/pull/29
