### ISSUE TITLE
Should gem line go at the top of Gemfile?

### ISSUE THREAD

**Issue by dideler** [bkeepers/dotenv-deployment#28]
The [dotenv readme](https://github.com/bkeepers/dotenv#readme) mentions (emphasis mine)

> Add this line **to the top of** your application's Gemfile:
```ruby
gem 'dotenv-rails', :groups => [:development, :test]
```

Whereas the [dotenv-deployment readme](https://github.com/bkeepers/dotenv-deployment#readme) says
> Add this line to your application's Gemfile:
```ruby
gem 'dotenv-deployment'
```

Should that line also be at the top of the Gemfile like advised for dotenv?

**Comment by bkeepers** [comment]
This gem has been deprecated. See https://github.com/bkeepers/dotenv-deployment/pull/29
